language: generic
services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/clienttest -f ./client/Dockerfile.dev ./client

#script:
# - docker run -e CI=true $DOCKER_USERNAME/clienttest npm run test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io
  - docker build --no-cache -t $DOCKER_USERNAME/cont-client:latest ./client
#  - docker build -t $DOCKER_USERNAME/cont-nginx:latest ./nginx
#  - docker build -t $DOCKER_USERNAME/cont-server:latest ./server
#  - docker build -t $DOCKER_USERNAME/cont-worker:latest ./worker
  - docker push $DOCKER_USERNAME/cont-client:latest
#  - docker push $DOCKER_USERNAME/cont-nginx:latest
#  - docker push $DOCKER_USERNAME/cont-server:latest
#  - docker push $DOCKER_USERNAME/cont-worker:latest

